### PR TITLE
Update notification to prompt for a reboot after GPU switch as this i…

### PR DESCRIPTION
**Pull request by MW5638**
…s now required.

### CODE REVIEW

**Comment by flexiondotorg** [comment]
@mwilsonuid0 Can you double check this please? On my XPS 15 I can switch GPUs and the only requirement is log out and back in.

**Comment by mcdonc** [comment]
Can confirm on Lenovo P50 that a logout and relogin does not actually switch the driver; reboot still required after a dist-upgrade today.

**Comment by MW5638** [comment]
Retested to confirm, the switch does not actually work until reboot. You can verify this by running `nvidia-smi` after swapping to NVIDIA and logging out and back in.

**Comment by mcdonc** [comment]
Retested this today and a login and logout does now enable the proper driver.  I think this can be closed if @mwilsonuid0 confirms.

**Comment by flexiondotorg** [comment]
This issue is due to a bug in the nvidia drivers package for Ubuntu 18.04 and 18.10. See this post for details - https://discourse.ubuntu.com/t/call-for-testing-nvidia-prime-in-ubuntu-18-04-and-18-10/8207

As a result I will not be merging this pull request as `mate-optimus` behaves correctly, even `nvidia-settings` asks users to logout when drivers are switched 🙂

**Pull request closed without merging**
